version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: eezee
    versions:
    - 1.0.15
  rebase-strategy: disabled
